### ISSUE TITLE
Guidelines for translation

### ISSUE THREAD

**Issue by vedovelli** [brndnmtthws/hodlermanifesto#3]
Cool manifesto!

Do you have any guidelines regarding translation? I can translate it to pt_Br.

Thanks!

**Comment by brndnmtthws** [comment]
Wow, that would be great! I haven't even thought about this yet, so I'll have to put something together and get back to you.

**Comment by vedovelli** [comment]
I can start the translation if you say you'd publish in your domain!

**Comment by brndnmtthws** [comment]
Yeah, of course.

It looks like GitHub doesn't officially support any translation/i18n for pages: https://github.com/github/pages-gem/issues/401

However, just copy index.md to index_pt_Br.md and I will take care of the rest.

**Comment by vedovelli** [comment]
I will. Just hodl! >.<

**Comment by vedovelli** [comment]
PR sent!
